var nodemailer = require("nodemailer");
const configs = require("./configs");

var transport = nodemailer.createTransport({
  host: configs.MAIL_HOST,
  port: configs.MAIL_PORT,
  auth: {
    user: configs.MAIL_USER, //example of generated by Mailtrap
    pass: configs.MAIL_PASS, //example of generated by Mailtrap
  },
});

module.exports = {
  send: async function (email, message) {
    await transport.sendMail({
      from: "iamasystemadmin@gmail.com",
      to: email,
      subject: "THU NAY DE RESET PASS",
      html: `
            <a href=/authen/resetPassword/'+message+'>Vui lòng click vào đây để reset pasword: Hồ Thành Vinh - 2080600816</a>
                <a href="/authen/resetPassword/${message}">
                    <img src="https://i.imgur.com/GN4sfZ9.jpg" alt="Reset Password Image" style="width: 100%; max-width: 600px; height: auto;">
                </a>
            `,
    });
  },
};
